ALTER TABLE `service_benefits` ADD `icon` text;--> statement-breakpoint
ALTER TABLE `services` ADD `category` text;--> statement-breakpoint
ALTER TABLE `services` ADD `hero_eyebrow_en` text;--> statement-breakpoint
ALTER TABLE `services` ADD `hero_eyebrow_km` text;--> statement-breakpoint
ALTER TABLE `services` ADD `hero_title_en` text;--> statement-breakpoint
ALTER TABLE `services` ADD `hero_title_km` text;--> statement-breakpoint
ALTER TABLE `services` ADD `hero_summary_en` text;--> statement-breakpoint
ALTER TABLE `services` ADD `hero_summary_km` text;--> statement-breakpoint
ALTER TABLE `services` ADD `hero_image_key` text;--> statement-breakpoint
ALTER TABLE `services` ADD `about_title_en` text;--> statement-breakpoint
ALTER TABLE `services` ADD `about_title_km` text;--> statement-breakpoint
ALTER TABLE `services` ADD `about_body_en` text;--> statement-breakpoint
ALTER TABLE `services` ADD `about_body_km` text;--> statement-breakpoint
ALTER TABLE `services` ADD `about_image_key` text;--> statement-breakpoint
ALTER TABLE `services` ADD `duration_en` text;--> statement-breakpoint
ALTER TABLE `services` ADD `duration_km` text;--> statement-breakpoint
ALTER TABLE `services` ADD `recovery_en` text;--> statement-breakpoint
ALTER TABLE `services` ADD `recovery_km` text;--> statement-breakpoint
ALTER TABLE `services` ADD `visits_en` text;--> statement-breakpoint
ALTER TABLE `services` ADD `visits_km` text;--> statement-breakpoint
ALTER TABLE `services` ADD `consultation_en` text;--> statement-breakpoint
ALTER TABLE `services` ADD `consultation_km` text;--> statement-breakpoint
ALTER TABLE `services` ADD `cta_title_en` text;--> statement-breakpoint
ALTER TABLE `services` ADD `cta_title_km` text;--> statement-breakpoint
ALTER TABLE `services` ADD `cta_description_en` text;--> statement-breakpoint
ALTER TABLE `services` ADD `cta_description_km` text;--> statement-breakpoint
ALTER TABLE `services` ADD `primary_cta_label_en` text;--> statement-breakpoint
ALTER TABLE `services` ADD `primary_cta_label_km` text;--> statement-breakpoint
ALTER TABLE `services` ADD `secondary_cta_label_en` text;--> statement-breakpoint
ALTER TABLE `services` ADD `secondary_cta_label_km` text;--> statement-breakpoint
ALTER TABLE `services` ADD `meta_title_en` text;--> statement-breakpoint
ALTER TABLE `services` ADD `meta_title_km` text;--> statement-breakpoint
ALTER TABLE `services` ADD `meta_description_en` text;--> statement-breakpoint
ALTER TABLE `services` ADD `meta_description_km` text;