import type { PublicLanguage } from '@/services/public-content';

/**
 * Interface copy for the public site: section headings, empty and error states,
 * and accessible names. CMS-owned text (clinic, services, doctors, branches,
 * showcases) is translated by the API and never appears here.
 *
 * Page components read this through `usePublicLanguage()`, so every string on a
 * public page follows the visitor's chosen language.
 */
export function publicUiCopy(language: PublicLanguage) {
  const isKm = language === 'km';
  return {
    about: {
      differenceTitle: isKm ? 'អ្វីដែលធ្វើឱ្យយើងខុសប្លែក' : 'What Makes Us Different',
      errorBody: isKm ? 'សូមព្យាយាមម្ដងទៀត ដើម្បីផ្ទុករឿងរ៉ាវគ្លីនិកឡើងវិញ។' : 'Try again to refresh the clinic story.',
      errorTitle: isKm ? 'យើងមិនអាចផ្ទុកទំព័រអំពីយើងបានទេ' : 'We could not load the about page',
      loading: isKm ? 'កំពុងផ្ទុកទំព័រអំពីយើង' : 'Loading about page',
      loadingLabel: isKm ? 'កំពុងផ្ទុករឿងរ៉ាវគ្លីនិក' : 'Loading clinic story',
      unavailableBody: isKm ? 'សូមពិនិត្យប្រភពមាតិកា រួចព្យាយាមម្ដងទៀត។' : 'Please check the content source and try again.',
      unavailableTitle: isKm ? 'មាតិកាទំព័រអំពីយើងមិនមានទេ' : 'About page content is unavailable',
      viewProfile: isKm ? 'មើលប្រវត្តិរូប' : 'View profile',
      whyTitle: isKm ? 'ហេតុអ្វីជ្រើសរើសយើង' : 'Why Choose Us',
    },
    booking: {
      appointmentDetails: isKm ? 'ព័ត៌មានលម្អិតនៃការណាត់ជួប' : 'Appointment Details',
      heroEyebrow: isKm ? 'ស្នើសុំការណាត់ជួប' : 'Appointment request',
      selectDoctor: isKm ? 'ជ្រើសរើសវេជ្ជបណ្ឌិត (ជាជម្រើស)' : 'Select Doctor (Optional)',
      availableTime: isKm ? 'ម៉ោងទំនេរ' : 'Available Time',
      chooseDateTime: isKm ? 'ជ្រើសរើសកាលបរិច្ឆេទ និងម៉ោង' : 'Choose Date & Time',
      date: isKm ? 'កាលបរិច្ឆេទ' : 'Date',
      doctor: isKm ? 'វេជ្ជបណ្ឌិត' : 'Doctor',
      duration: isKm ? 'រយៈពេល' : 'Duration',
      errorBody: isKm ? 'សូមព្យាយាមម្ដងទៀត ដើម្បីផ្ទុកទម្រង់ណាត់ជួបឡើងវិញ។' : 'Try again to refresh the appointment form.',
      errorTitle: isKm ? 'យើងមិនអាចផ្ទុកការកក់ណាត់ជួបបានទេ' : 'We could not load booking',
      loading: isKm ? 'កំពុងផ្ទុកទម្រង់ស្នើសុំណាត់ជួប' : 'Loading appointment request form',
      selectBranch: isKm ? 'ជ្រើសរើសសាខា' : 'Select Branch',
      selectMinute: isKm ? 'ជ្រើសរើសនាទី' : 'Select Minute',
      selectService: isKm ? 'ជ្រើសរើសសេវាកម្ម' : 'Select Service',
      service: isKm ? 'សេវាកម្ម' : 'Service',
      spamProtection: isKm ? 'ការផ្ទៀងផ្ទាត់ប្រឆាំងសារឥតបានការ' : 'Spam protection verification',
      verificationFailed: isKm ? 'មិនអាចផ្ទុកការផ្ទៀងផ្ទាត់សុវត្ថិភាពបានទេ។ សូមពិនិត្យបណ្ដាញអ៊ីនធឺណិត ឬព្យាយាមម្ដងទៀត។' : 'Security verification could not load. Please check your network or try again.',
      verificationLoading: isKm ? 'កំពុងផ្ទុកការផ្ទៀងផ្ទាត់…' : 'Loading verification challenge…',
      verificationRetry: isKm ? 'ព្យាយាមផ្ទៀងផ្ទាត់ម្ដងទៀត' : 'Retry verification',
      time: isKm ? 'ម៉ោង' : 'Time',
      unavailableBody: isKm ? 'សូមពិនិត្យប្រភពមាតិកា រួចព្យាយាមម្ដងទៀត។' : 'Please check the content source and try again.',
      unavailableTitle: isKm ? 'ព័ត៌មានណាត់ជួបមិនមានទេ' : 'Appointment information is unavailable',
      yourInformation: isKm ? 'ព័ត៌មានរបស់អ្នក' : 'Your Information',
    },
    branches: {
      address: isKm ? 'អាសយដ្ឋាន' : 'Address',
      errorBody: isKm ? 'សូមព្យាយាមម្ដងទៀត ដើម្បីផ្ទុកទីតាំងគ្លីនិកឡើងវិញ។' : 'Try again to refresh the clinic locations.',
      errorTitle: isKm ? 'យើងមិនអាចផ្ទុកទំព័រសាខាបានទេ' : 'We could not load the branches page',
      loading: isKm ? 'កំពុងផ្ទុកទីតាំងគ្លីនិក' : 'Loading clinic locations',
      openingHours: isKm ? 'ម៉ោងបើកទ្វារ' : 'Opening hours',
      photoView: isKm ? 'រូបថត' : 'Photo',
      satelliteView: isKm ? 'ផែនទីផ្កាយរណប' : 'Satellite Map',
      phone: isKm ? 'ទូរស័ព្ទ' : 'Phone',
      unavailableBody: isKm ? 'សូមពិនិត្យប្រភពមាតិកា រួចព្យាយាមម្ដងទៀត។' : 'Please check the content source and try again.',
      unavailableTitle: isKm ? 'ព័ត៌មានសាខាមិនមានទេ' : 'Branch information is unavailable',
    },
    common: {
      error: isKm ? 'មានបញ្ហា' : 'Error',
      noContent: isKm ? 'គ្មានមាតិកា' : 'No content',
      retry: isKm ? 'ព្យាយាមម្ដងទៀត' : 'Retry',
    },
    contact: {
      bookCta: isKm ? 'ស្នើសុំការណាត់ជួប' : 'Book an appointment request',
      bookIntro: isKm ? 'ប្រើទម្រង់ស្នើសុំណាត់ជួបរបស់យើង ដើម្បីជ្រើសរើសសេវាកម្ម សាខា កាលបរិច្ឆេទ និងម៉ោងដែលអ្នកចង់បាន។ គ្លីនិកនឹងពិនិត្យសំណើរបស់អ្នក មុននឹងបញ្ជាក់។' : 'Use our appointment request form to choose your preferred service, branch, date, and time. The clinic will review your request before confirming it.',
      directions: isKm ? 'មើលផ្លូវទៅ' : 'Get Directions',
      hoursLabel: isKm ? 'ម៉ោង៖' : 'Hours:',
      errorBody: isKm ? 'សូមព្យាយាមម្ដងទៀត ដើម្បីផ្ទុកព័ត៌មានទំនាក់ទំនងឡើងវិញ។' : 'Try again to refresh the contact information.',
      errorTitle: isKm ? 'យើងមិនអាចផ្ទុកទំព័រទំនាក់ទំនងបានទេ' : 'We could not load the contact page',
      loading: isKm ? 'កំពុងផ្ទុកព័ត៌មានទំនាក់ទំនង' : 'Loading contact information',
      satelliteMap: isKm ? 'ផែនទីផ្កាយរណប' : 'Google Satellite',
      unavailableBody: isKm ? 'សូមពិនិត្យប្រភពមាតិកា រួចព្យាយាមម្ដងទៀត។' : 'Please check the content source and try again.',
      unavailableTitle: isKm ? 'មាតិកាទំព័រទំនាក់ទំនងមិនមានទេ' : 'Contact page content is unavailable',
    },
    doctorDetail: {
      noDoctor: isKm ? 'គ្មានវេជ្ជបណ្ឌិត' : 'No doctor',
      viewAllDoctors: isKm ? 'មើលវេជ្ជបណ្ឌិតទាំងអស់' : 'View All Doctors',
      errorBody: isKm ? 'សូមព្យាយាមម្ដងទៀត ដើម្បីផ្ទុកព័ត៌មានប្រវត្តិរូបឡើងវិញ។' : 'Try again to refresh the profile information.',
      errorTitle: isKm ? 'យើងមិនអាចផ្ទុកប្រវត្តិរូបវេជ្ជបណ្ឌិតនេះបានទេ' : 'We could not load this doctor profile',
      loading: isKm ? 'កំពុងផ្ទុកប្រវត្តិរូបវេជ្ជបណ្ឌិត' : 'Loading doctor profile',
      unavailableBody: isKm ? 'សូមត្រឡប់ទៅទំព័រវេជ្ជបណ្ឌិត ហើយជ្រើសរើសប្រវត្តិរូបផ្សេង។' : 'Please return to the doctors page and choose another profile.',
      unavailableTitle: isKm ? 'ប្រវត្តិរូបវេជ្ជបណ្ឌិតមិនមានទេ' : 'Doctor profile is unavailable',
    },
    doctors: {
      errorBody: isKm ? 'សូមព្យាយាមម្ដងទៀត ដើម្បីផ្ទុកប្រវត្តិរូបវេជ្ជបណ្ឌិតឡើងវិញ។' : 'Try again to refresh the doctor profiles.',
      errorTitle: isKm ? 'យើងមិនអាចផ្ទុកទំព័រវេជ្ជបណ្ឌិតបានទេ' : 'We could not load the doctors page',
      loading: isKm ? 'កំពុងផ្ទុកទំព័រវេជ្ជបណ្ឌិត' : 'Loading doctors page',
      loadingLabel: isKm ? 'កំពុងផ្ទុកប្រវត្តិរូបវេជ្ជបណ្ឌិត' : 'Loading doctor profiles',
      profilesLabel: isKm ? 'ប្រវត្តិរូបវេជ្ជបណ្ឌិត' : 'Doctor profiles',
      teamImageAlt: isKm ? 'ក្រុមការងារគ្លីនិកធ្មេញ អារុណរះ' : 'Arunreah Dental Clinic team',
      unavailableBody: isKm ? 'សូមពិនិត្យប្រភពមាតិកា រួចព្យាយាមម្ដងទៀត។' : 'Please check the content source and try again.',
      unavailableTitle: isKm ? 'ប្រវត្តិរូបវេជ្ជបណ្ឌិតមិនមានទេ' : 'Doctor profiles are unavailable',
    },
    landing: {
      branchesLabel: isKm ? 'សាខាគ្លីនិក' : 'Clinic branches',
      branchesTitle: isKm ? 'សាខា' : 'Branches',
      errorBody: isKm ? 'សូមព្យាយាមម្ដងទៀត ដើម្បីផ្ទុកមាតិកាគ្លីនិកឡើងវិញ។' : 'Try again to refresh the clinic content.',
      errorTitle: isKm ? 'យើងមិនអាចផ្ទុកទំព័រដើមបានទេ' : 'We could not load the landing page',
      loading: isKm ? 'កំពុងផ្ទុកទំព័រដើម' : 'Loading landing page',
      loadingLabel: isKm ? 'កំពុងផ្ទុកមាតិកាគ្លីនិក' : 'Loading clinic content',
      scrollServicesLeft: isKm ? 'រំកិលសេវាកម្មទៅឆ្វេង' : 'Scroll services left',
      scrollServicesRight: isKm ? 'រំកិលសេវាកម្មទៅស្ដាំ' : 'Scroll services right',
      scrollSpecialistsLeft: isKm ? 'រំកិលទន្តបណ្ឌិតទៅឆ្វេង' : 'Scroll specialists left',
      scrollSpecialistsRight: isKm ? 'រំកិលទន្តបណ្ឌិតទៅស្ដាំ' : 'Scroll specialists right',
      seeAllBranches: isKm ? 'មើលសាខាទាំងអស់' : 'See All Branches',
      seeAllDoctors: isKm ? 'មើលវេជ្ជបណ្ឌិតទាំងអស់' : 'See All Doctors',
      seeAllServices: isKm ? 'មើលសេវាកម្មទាំងអស់' : 'See All Services',
      servicesEyebrow: isKm ? 'អ្វីដែលយើងផ្ដល់ជូន' : 'What We Offer',
      servicesTitle: isKm ? 'សេវាកម្មរបស់យើង' : 'Our Services',
      specialistsEyebrow: isKm ? 'ក្រុមជំនាញ' : 'Expert Team',
      srHeading: isKm ? 'គ្លីនិកធ្មេញ អារុណរះ' : 'Arunreah Dental Clinic',
      viewShowcases: isKm ? 'មើលស្នាដៃទាំងអស់' : 'View Show Cases',
      showcaseEyebrow: isKm ? 'រឿងរ៉ាវអ្នកជំងឺ និងការណែនាំពីគ្លីនិក' : 'Patient stories & clinic guidance',
      showcaseTitle: isKm ? 'ស្នាដៃថ្មីៗ' : 'Latest Showcase',
      specialistsTitle: isKm ? 'ជួបជាមួយក្រុមទន្តបណ្ឌិតរបស់យើង' : 'Meet Our Specialists',
      unavailableBody: isKm ? 'សូមពិនិត្យប្រភពមាតិកា រួចព្យាយាមម្ដងទៀត។' : 'Please check the content source and try again.',
      unavailableTitle: isKm ? 'មាតិកាទំព័រដើមមិនមានទេ' : 'Landing page content is unavailable',
    },
    layout: {
      footerBranches: isKm ? 'សាខារបស់យើង' : 'Our Branches',
      homeLink: isKm ? 'ទំព័រដើម គ្លីនិកធ្មេញ អារុណរះ' : 'Arunreah Dental Clinic home',
      languageSelector: isKm ? 'ការជ្រើសរើសភាសា' : 'Language selector',
      closeMenu: isKm ? 'បិទម៉ឺនុយ' : 'Close navigation menu',
      mobileNavigation: isKm ? 'ម៉ឺនុយមេសម្រាប់ទូរស័ព្ទ' : 'Mobile primary navigation',
      openMenu: isKm ? 'បើកម៉ឺនុយ' : 'Open navigation menu',
      primaryNavigation: isKm ? 'ម៉ឺនុយមេ' : 'Primary navigation',
      skipToContent: isKm ? 'រំលងទៅមាតិកាចម្បង' : 'Skip to main content',
      switchToEnglish: isKm ? 'ប្ដូរទៅភាសាអង់គ្លេស' : 'Switch to English',
      switchToKhmer: isKm ? 'ប្ដូរទៅភាសាខ្មែរ' : 'Switch to Khmer',
    },
    serviceDetail: {
      viewService: isKm ? 'មើលសេវាកម្ម' : 'View Service',
      backToServices: isKm ? 'ត្រឡប់ទៅសេវាកម្ម' : 'Back to Services',
      errorBody: isKm ? 'សូមព្យាយាមម្ដងទៀត ដើម្បីផ្ទុកព័ត៌មានព្យាបាលឡើងវិញ។' : 'Try again to refresh the treatment information.',
      errorTitle: isKm ? 'យើងមិនអាចផ្ទុកសេវាកម្មនេះបានទេ' : 'We could not load this service',
      loading: isKm ? 'កំពុងផ្ទុកព័ត៌មានព្យាបាល' : 'Loading treatment information',
      unavailableBody: isKm ? 'សូមត្រឡប់ទៅទំព័រសេវាកម្ម ហើយជ្រើសរើសការព្យាបាលផ្សេង។' : 'Please return to the services page and choose another treatment.',
      unavailableTitle: isKm ? 'ព័ត៌មានលម្អិតនៃសេវាកម្មមិនមានទេ' : 'Service detail is unavailable',
    },
    services: {
      heroEyebrow: isKm ? 'ការព្យាបាលរបស់យើង' : 'Our Treatments',
      learnMore: isKm ? 'ស្វែងយល់បន្ថែម' : 'Learn More',
      errorBody: isKm ? 'សូមព្យាយាមម្ដងទៀត ដើម្បីផ្ទុកបញ្ជីសេវាកម្មឡើងវិញ។' : 'Try again to refresh the service list.',
      errorTitle: isKm ? 'យើងមិនអាចផ្ទុកទំព័រសេវាកម្មបានទេ' : 'We could not load the services page',
      loading: isKm ? 'កំពុងផ្ទុកទំព័រសេវាកម្ម' : 'Loading services page',
      loadingLabel: isKm ? 'កំពុងផ្ទុកសេវាកម្មព្យាបាល' : 'Loading treatments',
      unavailableBody: isKm ? 'សូមពិនិត្យប្រភពមាតិកា រួចព្យាយាមម្ដងទៀត។' : 'Please check the content source and try again.',
      unavailableTitle: isKm ? 'ព័ត៌មានសេវាកម្មមិនមានទេ' : 'Service information is unavailable',
    },
    showcaseDetail: {
      errorBody: isKm ? 'វាប្រហែលជាមិនត្រូវបានផ្សព្វផ្សាយទៀតទេ។' : 'It may no longer be published.',
      errorTitle: isKm ? 'ស្នាដៃនេះមិនមានទេ' : 'This showcase is unavailable',
      loading: isKm ? 'កំពុងផ្ទុកអត្ថបទស្នាដៃ' : 'Loading showcase article',
      notFound: isKm ? 'រកមិនឃើញ' : 'Not found',
      related: isKm ? 'ស្នាដៃពាក់ព័ន្ធ' : 'Related Showcases',
    },
    showcases: {
      empty: isKm ? 'មិនទាន់មានស្នាដៃនៅពេលនេះទេ។' : 'No showcases are available right now.',
      errorBody: isKm ? 'សូមព្យាយាមម្ដងទៀត ដើម្បីផ្ទុករឿងរ៉ាវថ្មីៗពីគ្លីនិកឡើងវិញ។' : 'Try again to refresh the latest clinic stories.',
      errorTitle: isKm ? 'យើងមិនអាចផ្ទុកស្នាដៃបានទេ' : 'We could not load showcases',
      heroEyebrow: isKm ? 'ស្នាដៃរបស់យើង' : 'Our work',
      heroTitle: isKm ? 'ស្នាដៃថ្មីៗ' : 'Latest Showcases',
      loading: isKm ? 'កំពុងផ្ទុកស្នាដៃគ្លីនិក' : 'Loading clinic showcases',
      readMore: isKm ? 'អានស្នាដៃ' : 'Read showcase',
    },
  };
}

export type PublicUiCopy = ReturnType<typeof publicUiCopy>;
